### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Gavin456b** [Poulpynou/dawnoftimebuilder#51]
Newest update is completely broken, game won't even launch. Removing or reverting to old version fixes crash.

[crash-2024-08-21_18.39.26-client.txt](https://github.com/user-attachments/files/16700926/crash-2024-08-21_18.39.26-client.txt)

**Comment by TheGoldenWorld** [comment]
Hi ! The crash report do not mention Dawn of Time and you play with a LOT of mods. The problem may not come from our mod but another one that inject data in DoT and make your game crash.  I would need to test your modpack to find the issue so if you want to join our discord it could be great ! https://discord.gg/dawn-of-time-303974483591692289

**Comment by Gavin456b** [comment]
Yes, however the crash stops when reverting to the previous version of Dawn of Time. It could be a conflict with another mod but it is definitely specific to the newest version. I will test with just Dawn of Time installed.

**Comment by Gavin456b** [comment]
Tested with just Dawn of Time installed and it works, so it must be a conflict with another mod, however due to how many I have that will be hard to figure out

**Comment by Gavin456b** [comment]
It appears to be an interaction with the mod "Every Compat (Wood Good)". Removing it and nothing else fixes the crash, possibly due to the DotBe rewrite. Reported to Every Compat author as well.

Per my debug log I found this line: 

"Failed to create mod instance. ModID: everycomp, class net.mehvahdjukaar.every_compat.forge.EveryCompatForge
java.lang.NoSuchFieldError: DOT_TAB
	at net.mehvahdjukaar.every_compat.modules.forge.dawn_of_time.DawnOfTimeModule.<init>(DawnOfTimeModule.java:55) ~[everycomp-1.20-2.6.73.jar%23536!/:?]
	at net.mehvahdjukaar.every_compat.EveryCompat.addModule(EveryCompat.java:181) ~[everycomp-1.20-2.6.73.jar%23536!/:?]
	at net.mehvahdjukaar.every_compat.forge.EveryCompatForge.<init>(EveryCompatForge.java:83) ~[everycomp-1.20-2.6.73.jar%23536!/:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.7.jar%23736!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.7.jar%23735!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]"

**Comment by PierreChag** [comment]
Hey !
Yes it makes sence. Wood Good has to code some stuff to add other version of our blocks. Because we change the code, their code (that uses ours) is broken. The problem has to be fixed on their side.
I will contact them and see what we can do !

**Comment by Gavin456b** [comment]
They let me know the issue was just fixed in latest patch! Thanks for your help.
