### ISSUE TITLE
Server crashes on startup, Forge 47.3.5, DOTB 1.5.8

### ISSUE THREAD

**Issue by shadow7483147** [Poulpynou/dawnoftimebuilder#52]
[debug.log](https://github.com/user-attachments/files/16734827/debug.log)

Using a barebones Forge server with only Dawn of Time Builder 1.5.8 and its dependencies (obtained via Prism launcher), the server crashes when trying to load the mod.

Shortlog:
```
[23Aug2024 20:36:57.309] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.3.5, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[23Aug2024 20:36:57.313] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.4 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[23Aug2024 20:36:57.444] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[23Aug2024 20:36:57.503] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Shadow86/Downloads/dawnoftime-test/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[23Aug2024 20:36:57.676] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Shadow86\Downloads\dawnoftime-test\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.5\fmlcore-1.20.1-47.3.5.jar is missing mods.toml file
[23Aug2024 20:36:57.678] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Shadow86\Downloads\dawnoftime-test\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.5\javafmllanguage-1.20.1-47.3.5.jar is missing mods.toml file
[23Aug2024 20:36:57.680] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Shadow86\Downloads\dawnoftime-test\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.5\lowcodelanguage-1.20.1-47.3.5.jar is missing mods.toml file
[23Aug2024 20:36:57.683] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Shadow86\Downloads\dawnoftime-test\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.5\mclanguage-1.20.1-47.3.5.jar is missing mods.toml file
[23Aug2024 20:36:57.843] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 8 dependencies adding them to mods collection
[23Aug2024 20:36:58.671] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[23Aug2024 20:36:58.675] [main/ERROR] [mixin/]: Mixin config yacl.mixins.json does not specify "minVersion" property
[23Aug2024 20:36:58.681] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[23Aug2024 20:37:02.370] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 47.3.5, for MC 1.20.1 with MCP 20230612.114412
[23Aug2024 20:37:02.372] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v47.3.5 Initialized
[23Aug2024 20:37:02.377] [modloading-worker-0/INFO] [YetAnotherConfigLib/]: Config file 'C:\Users\Shadow86\Downloads\dawnoftime-test\config\dawnoftimebuilder-config.json5' does not exist. Creating it with default values.
[23Aug2024 20:37:02.377] [modloading-worker-0/INFO] [YetAnotherConfigLib/]: Config file 'C:\Users\Shadow86\Downloads\dawnoftime-test\config\yacl.json5' does not exist. Creating it with default values.
[23Aug2024 20:37:02.377] [modloading-worker-0/INFO] [YetAnotherConfigLib/]: Serializing class dev.isxander.yacl3.platform.YACLConfig to 'C:\Users\Shadow86\Downloads\dawnoftime-test\config\yacl.json5'
[23Aug2024 20:37:02.377] [modloading-worker-0/INFO] [YetAnotherConfigLib/]: Serializing class org.dawnoftimebuilder.DoTBConfig to 'C:\Users\Shadow86\Downloads\dawnoftime-test\config\dawnoftimebuilder-config.json5'
[23Aug2024 20:37:02.513] [modloading-worker-0/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/color/block/BlockColors for invalid dist DEDICATED_SERVER
[23Aug2024 20:37:02.513] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: dawnoftimebuilder, class org.dawnoftimebuilder.DoTBForge
java.lang.RuntimeException: Attempted to load class net/minecraft/client/color/block/BlockColors for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.3.5.jar%2369!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3754) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2442) ~[?:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:75) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.lambda$getListenerListInternal$0(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:61) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.LockHelper.get(LockHelper.java:44) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.LockHelper.computeIfAbsent(LockHelper.java:39) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:56) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:50) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:276) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:269) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:163) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:86) ~[eventbus-6.0.5.jar%2352!/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:86) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.5.jar%2352!/:?]
	at org.dawnoftimebuilder.DoTBForge.<init>(DoTBForge.java:30) ~[DawnOfTimeBuilder-forge-1.20.1-1.5.8.jar%23103!/:1.5.7]
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.5.jar%23109!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.5.jar%23108!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[23Aug2024 20:37:02.521] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
```

**Comment by shadow7483147** [comment]
> Also occurs on 1.5.7, going to see how far it's happening..
> 
> Yep, it's just 1.5.7 and 1.5.8.

Nevermind, I misread the logfile. It's 1.5.8 only. (Which for some reason, is also 1.5.7)
`	at org.dawnoftimebuilder.DoTBForge.<init>(DoTBForge.java:30) ~[DawnOfTimeBuilder-forge-1.20.1-1.5.8.jar%23103!/:1.5.7]`

**Comment by TheGoldenWorld** [comment]
Hi ! Thanks for your bug report ! This new version of the mod seems to struggle when used on a server, but we haven't succeeded in finding out exactly where the problem comes from, even though we have gathered a few crash reports. We will continue to investigate further and try to isolate the issue :)

**Comment by ionutsoran** [comment]
[minecraft/Main]: Failed to start the minecraft server
26.08 09:57:30 [Server] INFO net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
26.08 09:57:30 [Server] INFO 	DawnOfTimeBuilder (dawnoftimebuilder) has failed to load correctly
26.08 09:57:30 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/color/block/BlockColors for invalid dist DEDICATED_SERVER
26.08 09:57:30 [Server] INFO ]


If this info helps you I have the same issue with 1.5.8 version. I am using forge version 47.2.0 and minecraft 1.20.1

**Comment by TheGoldenWorld** [comment]
Hi ! Thanks for your bug report ! I found this same line "INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/color/block/BlockColors for invalid dist DEDICATED_SERVER" on the previous crash report, this may be the issue ! 
I'm going to check that with our team :)

**Comment by Stiles52** [comment]
Hey, I also have the same problem. I'll send you my data if it helps you fix the problem. We are running arclight-forge-1.20.1-1.0.5. 
[crash-2024-08-26_15.15.43-fml.txt](https://github.com/user-attachments/files/16749102/crash-2024-08-26_15.15.43-fml.txt)

**Comment by Devilswarchild** [comment]
I will also post my server crash report here in the hopes we can get a working update soonish.

https://mclo.gs/EaBaJPN

also im on forge version 47.3.7 due to Biomes We've gone

For MineColonies: Dimensional Adventure (unreleased update)

**Comment by TheGoldenWorld** [comment]
Thanks to both of you ! This genkidama of crash report is really helping !

**Comment by Devilswarchild** [comment]
> Thanks to both of you ! This genkidama of crash report is really helping !

You are Welcome (from this modpack dev ^_^)

**Comment by Saturnxs** [comment]
Hi! I'm setting a forge 47.3.0 server (MC 1.20.1) and using the latest version of the mod. Hope this crash report will help you!

[crash-2024-08-28_23.54.20-fml.txt](https://github.com/user-attachments/files/16790148/crash-2024-08-28_23.54.20-fml.txt)

**Comment by MokahTGS** [comment]
Crashing my server on load.

Forge 47.3.1
DawnOfTimeBuilder-forge-1.20.1-1.5.8

Crash log: https://pastebin.com/954YP3sq

**Comment by HydrolienF** [comment]
To reproduce, run `./gradlew server` on branch 1.20.1-multiloader. (As said by multiple user, it crash on load)
It's probably a config about client only classes that have been lost in the multiloader transition.

To avoid the bug, don't use the `1.5.8` for multiplayer on Forge. The 1.5.7 should work find.
