### ISSUE TITLE
Initializing game error fabric 1.20.1

### ISSUE THREAD

**Issue by Ureiah** [Poulpynou/dawnoftimebuilder#53]
[crash-2024-09-03_16.50.12-client.txt](https://github.com/user-attachments/files/16856024/crash-2024-09-03_16.50.12-client.txt)

I was trying to make a modpack and i discovered the conflict after narrowing down the mods. DoT conflicts with Dramatic Doors by FizzWare. Is there some way that this can be fixed, so they play well together?

===

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dawnoftimebuilder' at 'org.dawnoftimebuilder.DoTBFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalArgumentException: Block{minecraft:air} has duplicate property: waterlogged
	at net.minecraft.class_2689$class_2690.method_11669(class_2689.java:152)
	at net.minecraft.class_2689$class_2690.method_11667(class_2689.java:127)
	at org.dawnoftimebuilder.block.templates.DoorBlockAA.method_9515(DoorBlockAA.java:26)
	at net.minecraft.class_2248.<init>(class_2248.java:181)
	at net.minecraft.class_2323.<init>(class_2323.java:53)
	at org.dawnoftimebuilder.block.templates.DoorBlockAA.<init>(DoorBlockAA.java:19)
	at org.dawnoftimebuilder.registry.DoTBBlocksRegistry.lambda$new$133(DoTBBlocksRegistry.java:182)
	at org.dawnoftimebuilder.RegistryImpls$FabricBlocksRegistry.registerWithItem(RegistryImpls.java:81)
	at org.dawnoftimebuilder.registry.DoTBBlocksRegistry.register(DoTBBlocksRegistry.java:432)
	at org.dawnoftimebuilder.registry.DoTBBlocksRegistry.<init>(DoTBBlocksRegistry.java:182)
	at org.dawnoftimebuilder.RegistryImpls$FabricBlocksRegistry.<init>(RegistryImpls.java:67)
	at org.dawnoftimebuilder.RegistryImpls.init(RegistryImpls.java:248)
	at org.dawnoftimebuilder.DoTBFabric.onInitialize(DoTBFabric.java:24)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more

**Comment by TheGoldenWorld** [comment]
Hello there, arf this bug again xD Everytime we update the mod it appears again. You should let the owner of DD aware of it, the bug do not come from our side. DD try to force the waterlogged feature on our doors and make the game crash. Thanks for your report tho !

**Comment by PierreChag** [comment]
The latest version of the mod is now compatible with DramaticDoors !
